on:
  push:
    branches:
      - "master" 
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - id: build-publish
      uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
      with:
        path: .
        install_command: 'echo "Skipping npm install because there is no package.json"'
        build_command: 'echo "Skipping build, static files already exist"'
